--DDL CRIACAO SCHEMA RAW
CREATE OR REPLACE TABLE apifundsexplorer.funds_explorer.raw_funds_ranking
(
  post_id STRING,
  ticker STRING,
  dividendo STRING,
  yeld STRING,
  media_yield_3m STRING,
  soma_yield_3m STRING,
  media_yield_6m STRING,
  soma_yield_6m STRING,
  media_yield_12m STRING,
  soma_yield_12m STRING,
  variacao_cotacao_mes STRING,
  rentabilidade STRING,
  rentabilidade_mes STRING,
  cotacao_fechamento STRING,
  soma_yield_ano_corrente STRING,
  ano STRING,
  vpa_yield STRING,
  vpa STRING,
  vpa_change STRING,
  pl STRING,
  vpa_rent STRING,
  vpa_rent_m STRING,
  yield_vpa_3m_sum STRING,
  yield_vpa_3m STRING,
  yield_vpa_6m_sum STRING,
  yield_vpa_6m STRING,
  yield_vpa_12m_sum STRING,
  yield_vpa_12m STRING,
  setor STRING,
  setor_slug STRING,
  valor STRING,
  liquidezmediadiaria STRING,
  patrimonio STRING,
  pvp STRING,
  p_vpa STRING,
  post_title STRING,
  ativos STRING,
  volatility STRING,
  numero_cotista STRING,
  tx_gestao STRING,
  tx_admin STRING,
  tx_performance STRING,
  scraping_date DATE,
  ingestion_timestamp STRING
)
PARTITION BY scraping_date;